org: web3ten0
app: serverless1
service: chat 
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  serverless-offline:
    httpPort: 4000
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true

resources:
  Resources:
    CatTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Chat
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  - ${file(./serverless/message.yml)}
  - ${file(./serverless/user.yml)}
